# Generated by Django 5.0.6 on 2024-06-13 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hostel", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="type",
        ),
        migrations.AddField(
            model_name="notification",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="hostel.tenant",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("bedsitter", "Bedsitter"),
                    ("one_bedroom", "One Bedroom"),
                    ("two_bedrooms", "Two Bedrooms"),
                    ("three_bedrooms", "Three Bedrooms"),
                ],
                default="Bedsitter",
                max_length=50,
            ),
        ),
    ]
