# Generated by Django 5.0.6 on 2024-07-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_tenant_password_alter_room_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
    ]
