# Generated by Django 5.0.6 on 2024-07-10 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0005_remove_room_description_roomdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitting_room_image', models.ImageField(blank=True, null=True, upload_to='room_description_images/')),
                ('bedroom_image', models.ImageField(blank=True, null=True, upload_to='room_description_images/')),
                ('kitchen_image', models.ImageField(blank=True, null=True, upload_to='room_description_images/')),
                ('bathroom_image', models.ImageField(blank=True, null=True, upload_to='room_description_images/')),
                ('description', models.TextField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='hostel.room')),
            ],
        ),
        migrations.DeleteModel(
            name='RoomDetail',
        ),
    ]
