# Generated by Django 5.0.6 on 2024-07-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0006_roomdescription_delete_roomdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdescription',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
