# Generated by Django 5.0.6 on 2024-07-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0007_alter_roomdescription_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='password',
        ),
        migrations.AddField(
            model_name='tenant',
            name='admin_number',
            field=models.CharField(default='exit', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='gender',
            field=models.CharField(default='Not specified', max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='major',
            field=models.CharField(default='exit', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='nationality',
            field=models.CharField(default='exit', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='parent',
            field=models.CharField(default='exit', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='passport',
            field=models.CharField(default='exit', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_image/'),
        ),
    ]
