# Generated by Django 5.0.6 on 2024-07-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0008_remove_tenant_password_tenant_admin_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='nationality',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='parent',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='passport',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
