# Generated by Django 5.0.6 on 2024-07-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0010_tenant_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
    ]
