# Generated by Django 5.0.6 on 2024-07-24 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0011_alter_room_number_alter_tenant_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hostel.tenant'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('tenant',), name='unique_tenant_booking'),
        ),
    ]
