# Generated by Django 5.0.6 on 2024-07-24 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0012_alter_booking_tenant_booking_unique_tenant_booking'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_tenant_booking',
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.room'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('room', 'tenant', 'check_in_date', 'check_out_date')},
        ),
    ]
