# Generated by Django 5.0.6 on 2024-07-25 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0015_room_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_booked',
        ),
    ]
