# Generated by Django 5.0.6 on 2024-07-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0017_remove_room_status_room_is_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_booked',
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
