# Generated by Django 5.0.6 on 2024-08-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0019_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='otherType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='type',
            field=models.CharField(choices=[('maintenance', 'Maintenance'), ('facility', 'Facility'), ('other', 'Other')], default='maintenance', max_length=20),
        ),
    ]
