# Generated by Django 5.0.6 on 2024-08-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0020_maintenance_othertype_maintenance_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='room_number',
            field=models.CharField(default='exit', max_length=10),
            preserve_default=False,
        ),
    ]
