# Generated by Django 5.0.6 on 2024-08-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0021_maintenance_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='bookings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hostel',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
