# Generated by Django 5.0.7 on 2024-09-01 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0022_hostel_bookings_hostel_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='bookings',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='views',
        ),
    ]
