# Generated by Django 5.0.7 on 2024-09-01 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0023_remove_hostel_bookings_remove_hostel_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_booking', to='hostel.booking'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hostel.room'),
        ),
    ]
