# Generated by Django 5.0.7 on 2024-09-01 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0024_room_booking_alter_booking_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='booking',
        ),
        migrations.AddField(
            model_name='room',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='hostel.tenant'),
        ),
    ]
