# Generated by Django 5.0.7 on 2024-09-15 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0030_rvpdownload'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='hostel.tenant'),
        ),
    ]
