# Generated by Django 5.0.7 on 2024-09-15 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0031_event_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rvpdownload',
            name='user',
        ),
        migrations.AddField(
            model_name='rvpdownload',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostel.tenant'),
        ),
    ]
