# Generated by Django 5.0.7 on 2024-09-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0032_remove_rvpdownload_user_rvpdownload_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='interaction_type',
            field=models.CharField(choices=[('register', 'Register'), ('contact', 'Contact')], default='contact', max_length=10),
        ),
    ]
