# Generated by Django 5.0.7 on 2024-09-16 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0033_facility_interaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='contact_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='FacilityRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_token', models.CharField(blank=True, max_length=12, unique=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='hostel.facility')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.tenant')),
            ],
        ),
    ]
