# Generated by Django 5.0.7 on 2024-09-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0034_facility_contact_info_facilityregistration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='contact_info',
            new_name='contact_name',
        ),
        migrations.AddField(
            model_name='facility',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
