# Generated by Django 5.0.7 on 2024-09-16 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0035_rename_contact_info_facility_contact_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facilityregistration',
            unique_together={('facility', 'tenant')},
        ),
    ]
