# Generated by Django 5.0.7 on 2024-09-16 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0036_alter_facilityregistration_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facilityregistration',
            unique_together=set(),
        ),
    ]
