# Generated by Django 5.0.7 on 2024-10-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0037_alter_facilityregistration_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='guardian_contact',
            field=models.CharField(default='exit', max_length=12),
            preserve_default=False,
        ),
    ]
