# Generated by Django 5.0.7 on 2024-10-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0038_tenant_guardian_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='position',
        ),
        migrations.AddField(
            model_name='tenant',
            name='relationship',
            field=models.CharField(default='exit', max_length=255),
            preserve_default=False,
        ),
    ]
