# Generated by Django 5.0.7 on 2024-10-08 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0039_remove_tenant_position_tenant_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityregistration',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.facility'),
        ),
    ]
