# Generated by Django 5.0.7 on 2024-10-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0040_alter_facilityregistration_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityregistration',
            name='registration_token',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
