# Generated by Django 5.0.7 on 2024-10-08 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0041_alter_facilityregistration_registration_token'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facilityregistration',
            unique_together={('tenant', 'facility')},
        ),
    ]
